# Generated by Django 5.2.11 on 2026-02-10 22:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deploy', '0001_initial'),
        ('plans', '0004_alter_plan_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Network')),
            ],
            options={
                'verbose_name': 'Private Network',
                'verbose_name_plural': 'Private Networks',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('status', models.CharField(choices=[('stopped', 'stopped'), ('queued', 'queued'), ('deploying', 'deploying'), ('failed', 'failed'), ('succeeded', 'succeeded'), ('stopping', 'stopping')], default='stopped', verbose_name='Deploy Status')),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Service', to='services.privatenetwork', verbose_name='Private Network')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan', verbose_name='Plan')),
                ('selected_deploy', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='deploy.deploy', verbose_name='Selected Deploy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('bind', models.CharField(max_length=255, verbose_name='Bind Directory')),
                ('mode', models.CharField(choices=[('read', 'Read-only'), ('write', 'Write-only'), ('readwrite', 'Read & Write')], default='readwrite', max_length=255, verbose_name='Mode Directory')),
                ('size_mb', models.PositiveIntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='services.service', verbose_name='Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bind', 'service'), name='unique_bind_per_service')],
            },
        ),
    ]
