# Generated by Django 5.2.11 on 2026-02-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='task_id',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Task ID'),
        ),
    ]
