# Generated by Django 5.2.11 on 2026-02-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deployed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='selected_deploy_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
