# Generated by Django 5.2 on 2026-02-21 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_deploy_updated_file_at'),
        ('services', '0003_service_deployed_at_service_selected_deploy_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='read_only',
            field=models.BooleanField(default=False, verbose_name='Read only'),
        ),
        migrations.AlterField(
            model_name='service',
            name='selected_deploy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='deploy.deploy', verbose_name='Selected Deploy'),
        ),
        migrations.AlterField(
            model_name='service',
            name='task_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Task ID'),
        ),
    ]
