# Generated by Django 6.0.6 on 2026-07-31 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_status_running'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volume',
            options={'verbose_name': 'Volume', 'verbose_name_plural': 'Volumes'},
        ),
        migrations.RemoveConstraint(
            model_name='volume',
            name='unique_bind_per_service',
        ),
        migrations.AddField(
            model_name='volume',
            name='default_bind',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Default Bind Directory'),
        ),
        migrations.AddField(
            model_name='volume',
            name='default_mode',
            field=models.CharField(blank=True, choices=[('read', 'Read-only'), ('write', 'Write-only'), ('readwrite', 'Read & Write')], default='readwrite', max_length=255, verbose_name='Default Mode'),
        ),
        migrations.AddField(
            model_name='volume',
            name='service_attachments',
            field=models.JSONField(blank=True, default=dict, help_text='Service ID → {bind, mode} mappings', verbose_name='Service Attachments'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_volumes', to='services.service', verbose_name='Legacy Service'),
        ),
        migrations.RemoveField(
            model_name='volume',
            name='bind',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='mode',
        ),
    ]
