# Generated by Django 6.0.5 on 2026-08-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_volume_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='default_mode',
            field=models.CharField(blank=True, choices=[('r', 'Read-only'), ('w', 'Write-only'), ('rw', 'Read & Write')], default='rw', max_length=255, verbose_name='Default Mode'),
        ),
    ]
