# Generated by Django 6.0.6 on 2026-08-06 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_volume_default_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Owning service. Volumes cannot be shared across services.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volumes', to='services.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='service_attachments',
            field=models.JSONField(blank=True, default=dict, help_text='Owning service ID → {bind, mode}. Only one service is allowed.', verbose_name='Service Attachments'),
        ),
    ]
