# Generated by Django 5.2.11 on 2026-09-25 01:34

import django.db.models.deletion
import services.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_service_lifecycle_generation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='serviceportreservation',
            new_name='services_se_host_po_f50e1a_idx',
            old_name='service_port_res_host_protocol_state',
        ),
        migrations.RenameIndex(
            model_name='serviceshare',
            new_name='services_se_service_773bee_idx',
            old_name='services_se_service_8a1f0e_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceshare',
            new_name='services_se_group_i_c92b87_idx',
            old_name='services_se_group_i_6c2b1a_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceshare',
            new_name='services_se_target__8f23fa_idx',
            old_name='services_se_target__9d3c2b_idx',
        ),
        migrations.RenameIndex(
            model_name='servicesharemember',
            new_name='services_se_share_i_463314_idx',
            old_name='services_se_share_i_mem01_idx',
        ),
        migrations.RenameIndex(
            model_name='shellauditevent',
            new_name='services_sh_service_3778ef_idx',
            old_name='svc_shell_audit_svc_created',
        ),
        migrations.RenameIndex(
            model_name='shellauditevent',
            new_name='services_sh_service_3a8ddb_idx',
            old_name='svc_shell_audit_svc_action',
        ),
        migrations.RenameIndex(
            model_name='shellauditevent',
            new_name='services_sh_user_id_07a498_idx',
            old_name='svc_shell_audit_user_created',
        ),
        migrations.RenameIndex(
            model_name='shellsession',
            new_name='services_sh_service_e35487_idx',
            old_name='services_sh_service_0c4f1e_idx',
        ),
        migrations.AlterField(
            model_name='databasecredential',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='databasecredential',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='databasecredential',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='databaseresource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='databaseresource',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='databaseresource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='service',
            name='active_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_services', to='services.servicerevision', verbose_name='Active Revision'),
        ),
        migrations.AlterField(
            model_name='service',
            name='build_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Build Configuration'),
        ),
        migrations.AlterField(
            model_name='service',
            name='desired_state',
            field=models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running'), ('deleted', 'Deleted')], default='stopped', max_length=16, verbose_name='Desired State'),
        ),
        migrations.AlterField(
            model_name='service',
            name='runtime_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Runtime Configuration'),
        ),
        migrations.AlterField(
            model_name='service',
            name='source_config',
            field=models.JSONField(blank=True, default=dict, help_text='Normalized source metadata. No runtime Docker state belongs here.', verbose_name='Source Configuration'),
        ),
        migrations.AlterField(
            model_name='service',
            name='source_kind',
            field=models.CharField(choices=[('archive', 'Archive'), ('git', 'Git'), ('dockerfile', 'Dockerfile'), ('image', 'Existing image'), ('compose', 'Compose'), ('catalog', 'Catalog'), ('generated', 'Generated')], default='archive', max_length=20, verbose_name='Source Kind'),
        ),
        migrations.AlterField(
            model_name='servicedatabasebinding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='servicedatabasebinding',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicedatabasebinding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='serviceendpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='serviceendpoint',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serviceendpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='serviceenvironmentvariable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='serviceenvironmentvariable',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serviceenvironmentvariable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='servicenetworkattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='servicenetworkattachment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicenetworkattachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='serviceportreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='serviceportreservation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serviceportreservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='serviceprocess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='serviceprocess',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serviceprocess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='artifact_file',
            field=models.FileField(blank=True, help_text='Immutable source artifact captured for this revision.', null=True, upload_to=services.models.revision_artifact_path),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicerevision',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='servicesecret',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='servicesecret',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicesecret',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='servicesecretversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='servicesecretversion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicesecretversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='serviceshare',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='serviceshare',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serviceshare',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='serviceshareevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='serviceshareevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serviceshareevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='servicesharemember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='servicesharemember',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicesharemember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='shellauditevent',
            name='action',
            field=models.CharField(choices=[('session_open', 'Session open'), ('session_close', 'Session close'), ('session_replace', 'Session replace'), ('command', 'Command'), ('command_dry_run', 'Command dry-run'), ('file_read', 'File read'), ('file_write', 'File write'), ('file_delete', 'File delete'), ('file_rename', 'File rename'), ('file_mkdir', 'File mkdir'), ('interactive_start', 'Interactive start'), ('interactive_exit', 'Interactive exit'), ('env_view', 'Env view'), ('health_view', 'Health view'), ('audit_search', 'Audit search'), ('audit_download', 'Audit download')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='shellauditevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='shellauditevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shellauditevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
