# Generated by Django 5.2 on 2025-08-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('queued', 'queued'), ('deploying', 'deploying'), ('failed', 'failed'), ('succeeded', 'succeeded')], default='created', verbose_name='Deploy Status'),
        ),
    ]
