# Generated by Django 5.2 on 2026-02-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='running',
        ),
    ]
