# Generated by Django 5.2 on 2025-08-10 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_deploy_status'),
        ('services', '0003_remove_service_network_remove_service_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.container', verbose_name='Service'),
        ),
    ]
