# Generated by Django 5.2 on 2026-02-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_remove_deploy_running'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='status',
        ),
    ]
