# Generated by Codex on 2026-07-06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deploy", "0004_alter_deploy_options"),
        ("services", "0005_service_deploy_started"),
    ]

    operations = [
        migrations.AddField(
            model_name="deploy",
            name="completed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Completion Time"),
        ),
        migrations.AddField(
            model_name="deploy",
            name="container_status",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="Container Status"),
        ),
        migrations.AddField(
            model_name="deploy",
            name="error_message",
            field=models.TextField(blank=True, default="", verbose_name="Error Message"),
        ),
        migrations.AddField(
            model_name="deploy",
            name="health_status",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="Health Status"),
        ),
        migrations.AddField(
            model_name="deploy",
            name="image_status",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="Image Status"),
        ),
        migrations.AddField(
            model_name="deploy",
            name="network_status",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="Network Status"),
        ),
        migrations.AddField(
            model_name="deploy",
            name="progress",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Deployment Progress"),
        ),
        migrations.AddField(
            model_name="deploy",
            name="rollback_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Not required"),
                    ("pending", "Pending"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                ],
                default="not_required",
                max_length=32,
                verbose_name="Rollback Status",
            ),
        ),
        migrations.AddField(
            model_name="deploy",
            name="stage",
            field=models.CharField(blank=True, default="idle", max_length=64, verbose_name="Deployment Stage"),
        ),
        migrations.AddField(
            model_name="deploy",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("rolling_back", "Rolling back"),
                    ("rolled_back", "Rolled back"),
                ],
                default="pending",
                max_length=32,
                verbose_name="Deployment Status",
            ),
        ),
        migrations.AddField(
            model_name="deploy",
            name="status_message",
            field=models.TextField(blank=True, default="", verbose_name="Status Message"),
        ),
        migrations.AddField(
            model_name="deploy",
            name="volume_status",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="Volume Status"),
        ),
        migrations.CreateModel(
            name="DeployLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("stage", models.CharField(max_length=64, verbose_name="Stage")),
                ("level", models.CharField(default="info", max_length=16, verbose_name="Level")),
                ("message", models.TextField(verbose_name="Message")),
                ("progress", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Progress")),
                ("details", models.JSONField(blank=True, null=True, verbose_name="Details")),
                (
                    "deploy",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="deploy.deploy",
                        verbose_name="Deploy",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployment_logs",
                        to="services.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deploy Log",
                "verbose_name_plural": "Deploy Logs",
                "ordering": ("created_at",),
            },
        ),
    ]
