# Generated by ChatGPT - migration to add cancel_requested
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0005_deployment_state_and_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='cancel_requested',
            field=models.BooleanField(default=False, verbose_name='Cancel Requested'),
        ),
    ]
