# Generated by Codex on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deploy", "0006_deploy_cancel_requested"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deploy",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("rolling_back", "Rolling back"),
                    ("rolled_back", "Rolled back"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=32,
                verbose_name="Deployment Status",
            ),
        ),
    ]
