# Generated by Django 5.2.11 on 2026-09-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0004_application_snapshot_and_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationinstance',
            name='stage',
            field=models.CharField(blank=True, default='pending', max_length=64),
        ),
    ]
