# Generated by Django 5.2 on 2026-10-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_catalog", "0007_restrict_installation_bindings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationinstance",
            name="network",
            field=__import__("django").db.models.OneToOneField(
                blank=True,
                null=True,
                on_delete=__import__("django").db.models.deletion.SET_NULL,
                related_name="application_instance",
                to="services.privatenetwork",
            ),
        ),
    ]
