# Generated by Django 5.2 on 2025-08-10 02:07

import auth_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='code',
            field=models.CharField(default=auth_users.models.get_random_code_8, max_length=8),
        ),
    ]
