# Generated by Django 6.0.5 on 2026-08-06 18:56

import auth_users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0002_alter_authcode_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_username', models.BooleanField(default=True, help_text='Allow username as an identifier')),
                ('allow_email', models.BooleanField(default=True, help_text='Allow email as an identifier')),
                ('allow_phone', models.BooleanField(default=True, help_text='Allow phone number as an identifier')),
                ('require_password', models.BooleanField(default=True, help_text='If True, password is required when the user has one set')),
                ('require_otp', models.BooleanField(default=True, help_text='If True, a one-time code (OTP) is required')),
                ('password_as_second_factor', models.BooleanField(default=True, help_text='If True and user has a password, after OTP ask for password (2FA). If False, password alone can be enough when require_otp=False')),
                ('allow_auto_signup', models.BooleanField(default=True, help_text='If user does not exist, automatically create the account')),
                ('auto_activate_on_signup', models.BooleanField(default=False, help_text='If True, newly created users become active immediately. If False, user stays inactive until admin activates or verification completes')),
                ('require_password_on_signup', models.BooleanField(default=True, help_text='When creating a new user, force them to set a password')),
                ('activate_after_successful_otp', models.BooleanField(default=True, help_text='After a valid OTP, set is_active=True (and mark email/phone verified)')),
                ('allow_username_recovery', models.BooleanField(default=True, help_text="Enable 'forgot username' flow")),
                ('recovery_via_email', models.BooleanField(default=True, help_text='Allow recovery by sending OTP to email')),
                ('recovery_via_phone', models.BooleanField(default=True, help_text='Allow recovery by sending OTP to phone')),
                ('otp_length', models.PositiveSmallIntegerField(default=8)),
                ('otp_expire_minutes', models.PositiveSmallIntegerField(default=5)),
                ('otp_max_attempts', models.PositiveSmallIntegerField(default=5, help_text='Max wrong OTP attempts before code is invalidated')),
                ('is_active', models.BooleanField(default=True, help_text='Only one settings row should be active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Login Settings',
                'verbose_name_plural': 'Login Settings',
            },
        ),
        migrations.AddField(
            model_name='authcode',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authcode',
            name='contact',
            field=models.CharField(blank=True, default='', help_text='Email or phone used when user is not yet resolved (recovery)', max_length=255),
        ),
        migrations.AddField(
            model_name='authcode',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login / Verify'), ('signup', 'Signup'), ('recovery', 'Username Recovery')], default='login', max_length=20),
        ),
        migrations.AddField(
            model_name='authcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='authcode',
            name='code',
            field=models.CharField(default=auth_users.models.get_random_code_8, max_length=16),
        ),
        migrations.AlterField(
            model_name='authcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='authcode',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null only for recovery when we only know email/phone', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='authcode',
            index=models.Index(fields=['user', 'purpose'], name='auth_users__user_id_b661e2_idx'),
        ),
        migrations.AddIndex(
            model_name='authcode',
            index=models.Index(fields=['contact', 'purpose'], name='auth_users__contact_36dcc3_idx'),
        ),
    ]
