# Generated by Django 6.0.6 on 2026-08-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0004_loginsettings_require_invite_for_signup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsettings',
            name='allow_login',
            field=models.BooleanField(default=True, help_text='Master switch: if False, all login/signup is blocked and custom message is shown'),
        ),
        migrations.AddField(
            model_name='loginsettings',
            name='allow_password_recovery',
            field=models.BooleanField(default=True, help_text="Enable 'forgot password' / reset password flow"),
        ),
        migrations.AddField(
            model_name='loginsettings',
            name='custom_login_closed_message',
            field=models.TextField(blank=True, default='', help_text='Message shown on login page when allow_login=False. Supports plain text.'),
        ),
        migrations.AddField(
            model_name='loginsettings',
            name='custom_login_closed_title',
            field=models.CharField(blank=True, default='Login temporarily unavailable', help_text='Title shown when login is closed', max_length=200),
        ),
        migrations.AddField(
            model_name='loginsettings',
            name='min_password_length',
            field=models.PositiveSmallIntegerField(default=6, help_text='Minimum password length enforced on set/reset'),
        ),
        migrations.AddField(
            model_name='loginsettings',
            name='password_recovery_via_email',
            field=models.BooleanField(default=True, help_text='Allow password reset by sending OTP to email'),
        ),
        migrations.AddField(
            model_name='loginsettings',
            name='password_recovery_via_phone',
            field=models.BooleanField(default=True, help_text='Allow password reset by sending OTP to phone'),
        ),
        migrations.AddField(
            model_name='loginsettings',
            name='require_confirm_password',
            field=models.BooleanField(default=True, help_text="Require 'confirm password' field when setting or resetting password"),
        ),
        migrations.AlterField(
            model_name='authcode',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login / Verify'), ('signup', 'Signup'), ('recovery', 'Username Recovery'), ('password_reset', 'Password Reset')], default='login', max_length=20),
        ),
        migrations.AlterField(
            model_name='loginsettings',
            name='recovery_via_email',
            field=models.BooleanField(default=True, help_text='Allow username recovery by sending OTP to email'),
        ),
        migrations.AlterField(
            model_name='loginsettings',
            name='recovery_via_phone',
            field=models.BooleanField(default=True, help_text='Allow username recovery by sending OTP to phone'),
        ),
    ]
