# Generated by Django 5.2.11 on 2026-09-25 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0006_loginlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginlog',
            new_name='auth_users__created_4ae7e4_idx',
            old_name='auth_users__created_f0a1b2_idx',
        ),
        migrations.RenameIndex(
            model_name='loginlog',
            new_name='auth_users__user_id_3d3e2c_idx',
            old_name='auth_users__user_id_c3d4e5_idx',
        ),
    ]
