# Generated by Django 5.2.11 on 2026-09-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelogentry',
            name='stream',
            field=models.CharField(choices=[('stdout', 'stdout'), ('stderr', 'stderr')], default='stdout', max_length=8),
        ),
        migrations.AlterField(
            model_name='servicelogstream',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('lost', 'Lost')], db_index=True, default='active', max_length=16),
        ),
        migrations.AddIndex(
            model_name='servicelogentry',
            index=models.Index(fields=['service_id', 'stream', '-ts'], name='svc_log_stream_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelogentry',
            index=models.Index(fields=['service_id', 'level', '-ts'], name='svc_log_level_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelogstream',
            index=models.Index(fields=['service_id', '-started_at'], name='logs_servic_service_46a2be_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelogstream',
            index=models.Index(fields=['container_id', 'status'], name='logs_servic_contain_1860a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicelogentry',
            constraint=models.UniqueConstraint(condition=models.Q(('fingerprint', ''), _negated=True), fields=('stream_id', 'fingerprint'), name='uniq_log_stream_fingerprint'),
        ),
    ]
