# Generated by Django 5.2 on 2025-08-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('DB', 'Database'), ('APP', 'Application'), ('READY', 'Ready-made')], default='APP', max_length=10, verbose_name='Plan Type'),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_per_hour',
            field=models.FloatField(default=0.0, help_text='Hourly pricing in Toman', verbose_name='Price Per Hour (Toman)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='storage_type',
            field=models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD')], default='HDD', max_length=10, verbose_name='Storage Type'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_cpu',
            field=models.PositiveIntegerField(verbose_name='Maximum CPU (vCPU)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_ram',
            field=models.PositiveIntegerField(verbose_name='Maximum RAM (MB)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_storage',
            field=models.PositiveIntegerField(verbose_name='Maximum Storage (GB)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Diamond', 'Diamond')], default='Bronze', help_text='Plan level name (e.g. Bronze, Silver, etc.)', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='platform',
            field=models.CharField(choices=[('php', 'PHP'), ('python', 'Python'), ('django', 'Django'), ('nextjs', 'Next.js'), ('nodejs', 'Node.js'), ('flask', 'Flask'), ('docker', 'Docker'), ('go', 'Go'), ('static', 'Static HTML/CSS'), ('vue', 'Vue.js'), ('angular', 'Angular'), ('react', 'React'), ('.net', '.NET')], help_text='Technology platform this plan supports', max_length=20, verbose_name='Platform'),
        ),
    ]
