# Generated by Django 5.2 on 2025-08-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_plan_price_plan_plan_type_plan_price_per_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='platform',
            field=models.CharField(choices=[('php', 'PHP'), ('python', 'Python'), ('django', 'Django'), ('nextjs', 'Next.js'), ('nodejs', 'Node.js'), ('flask', 'Flask'), ('docker', 'Docker'), ('go', 'Go'), ('static', 'Static HTML/CSS'), ('vue', 'Vue.js'), ('angular', 'Angular'), ('react', 'React'), ('dotnet', '.NET')], help_text='Technology platform this plan supports', max_length=20, verbose_name='Platform'),
        ),
    ]
