# Generated by Django 5.2.11 on 2026-02-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_plan_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_cpu',
            field=models.FloatField(verbose_name='Maximum CPU (vCPU)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_ram',
            field=models.FloatField(verbose_name='Maximum RAM (MB)'),
        ),
    ]
