# Generated by Django 5.2.11 on 2026-09-25 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_markdown_tree_assets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('order', 'title')},
        ),
        migrations.AlterModelOptions(
            name='documentasset',
            options={'ordering': ('-created_at',)},
        ),
    ]
