from django.urls import path
from .apis import DatabaseBindingsView, AgentCapabilitiesView,AgentExchangeView,AgentManifestView,AgentMeView,AgentOpenAPIView,AgentRootView,ConfigurationView,DatabaseCredentialsView,DeploymentActionView,DeploymentDetailView,DeploymentHelpView,DeploymentInspectView,DeploymentListCreateView,DeploymentLogsExportView,DeploymentLogsView,DeploymentRollbackView,DeploymentUploadView,EndpointConfigView,EnvironmentView,NetworkAttachmentsView,NetworkDetailView,NetworkListCreateView,PlanApplyView,PlanDetailView,PlanListView,PlanManagementView,RevisionDetailView,RevisionListView,RevisionRollbackView,SecretsView,ServiceActionView,ServiceDetailView,ServiceFromPlanView,ServiceListCreateView,ServiceLogsExportView,ServiceLogsView,ServiceMetricsView,ServiceStatusView,ShellCloseView,ShellCommandView,ShellFileView,ShellInfoView,ShellReplaceView,ShellSessionView,SkillDetailView,SkillIndexView,VolumeDetailView,VolumeListCreateView
app_name="agent"
urlpatterns=[
path("v1/",AgentRootView.as_view()),path("v1/skills",SkillIndexView.as_view()),path("v1/skills/<slug:skill_name>",SkillDetailView.as_view()),path("v1/auth/exchange",AgentExchangeView.as_view()),path("v1/auth/me",AgentMeView.as_view()),path("v1/capabilities",AgentCapabilitiesView.as_view()),path("v1/agent.md",AgentManifestView.as_view()),path("v1/openapi.json",AgentOpenAPIView.as_view()),
path("v1/services/from-plan",ServiceFromPlanView.as_view()),path("v1/services",ServiceListCreateView.as_view()),path("v1/services/<uuid:service_id>",ServiceDetailView.as_view()),
path("v1/services/<uuid:service_id>/start",ServiceActionView.as_view(),{"action":"start"}),path("v1/services/<uuid:service_id>/stop",ServiceActionView.as_view(),{"action":"stop"}),path("v1/services/<uuid:service_id>/restart",ServiceActionView.as_view(),{"action":"restart"}),path("v1/services/<uuid:service_id>/rebuild",ServiceActionView.as_view(),{"action":"rebuild"}),path("v1/services/<uuid:service_id>/purge-runtime",ServiceActionView.as_view(),{"action":"purge-runtime"}),path("v1/services/<uuid:service_id>/status",ServiceStatusView.as_view()),path("v1/services/<uuid:service_id>/metrics",ServiceMetricsView.as_view()),path("v1/services/<uuid:service_id>/logs",ServiceLogsView.as_view()),path("v1/services/<uuid:service_id>/logs/export",ServiceLogsExportView.as_view()),path("v1/services/<uuid:service_id>/configuration",ConfigurationView.as_view()),path("v1/services/<uuid:service_id>/environment",EnvironmentView.as_view()),path("v1/services/<uuid:service_id>/secrets",SecretsView.as_view()),path("v1/services/<uuid:service_id>/endpoints",EndpointConfigView.as_view()),path("v1/services/<uuid:service_id>/networks",NetworkAttachmentsView.as_view()),path("v1/services/<uuid:service_id>/databases",DatabaseBindingsView.as_view()),path("v1/services/<uuid:service_id>/database-credentials",DatabaseCredentialsView.as_view()),
path("v1/services/<uuid:service_id>/revisions",RevisionListView.as_view()),path("v1/services/<uuid:service_id>/revisions/<uuid:revision_id>",RevisionDetailView.as_view()),path("v1/services/<uuid:service_id>/revisions/<uuid:revision_id>/rollback",RevisionRollbackView.as_view()),path("v1/services/<uuid:service_id>/shell",ShellInfoView.as_view()),path("v1/services/<uuid:service_id>/shell/sessions",ShellSessionView.as_view()),path("v1/services/<uuid:service_id>/shell/sessions/<uuid:session_id>/commands",ShellCommandView.as_view()),path("v1/services/<uuid:service_id>/shell/sessions/<uuid:session_id>/close",ShellCloseView.as_view()),path("v1/services/<uuid:service_id>/shell/replace",ShellReplaceView.as_view()),path("v1/services/<uuid:service_id>/shell/files",ShellFileView.as_view()),path("v1/services/<uuid:service_id>/tools",RuntimeToolIndexView.as_view()),path("v1/services/<uuid:service_id>/tools/<str:tool_name>",RuntimeToolExecuteView.as_view()),
path("v1/plans",PlanListView.as_view()),path("v1/plans/<uuid:plan_id>",PlanDetailView.as_view()),path("v1/plans/<uuid:plan_id>/apply",PlanApplyView.as_view()),path("v1/plans/manage",PlanManagementView.as_view()),path("v1/plans/manage/<uuid:plan_id>",PlanManagementView.as_view()),
path("v1/networks",NetworkListCreateView.as_view()),path("v1/networks/<uuid:network_id>",NetworkDetailView.as_view()),path("v1/volumes",VolumeListCreateView.as_view()),path("v1/volumes/<uuid:volume_id>",VolumeDetailView.as_view()),
path("v1/deployments/help",DeploymentHelpView.as_view()),path("v1/deployments/inspect",DeploymentInspectView.as_view()),path("v1/deployments",DeploymentListCreateView.as_view()),path("v1/deployments/<uuid:deployment_id>",DeploymentDetailView.as_view()),path("v1/deployments/<uuid:deployment_id>/upload",DeploymentUploadView.as_view()),path("v1/deployments/<uuid:deployment_id>/start",DeploymentActionView.as_view(),{"action":"start"}),path("v1/deployments/<uuid:deployment_id>/cancel",DeploymentActionView.as_view(),{"action":"cancel"}),path("v1/deployments/<uuid:deployment_id>/redeploy",DeploymentActionView.as_view(),{"action":"redeploy"}),path("v1/deployments/<uuid:deployment_id>/rebuild",DeploymentActionView.as_view(),{"action":"rebuild"}),path("v1/deployments/<uuid:deployment_id>/rollback",DeploymentRollbackView.as_view()),path("v1/deployments/<uuid:deployment_id>/logs",DeploymentLogsView.as_view()),path("v1/deployments/<uuid:deployment_id>/logs/export",DeploymentLogsExportView.as_view())]
