"""Wagtail admin (snippet) registration for the deploy app."""
from __future__ import annotations

from django.conf import settings
from django.utils.translation import gettext_lazy as _

from cms.wagtail_admin.utils import panels_for, read_only_panels
from deploy.models import Deploy, DeployLog
from wagtail.permission_policies.base import ModelPermissionPolicy
from wagtail.snippets.views.snippets import SnippetViewSet, SnippetViewSetGroup


class DeployViewSet(SnippetViewSet):
    model = Deploy
    icon = "upload"
    menu_label = _("Deployments")
    menu_order = 104
    list_display = [
        "name",
        "service",
        "version",
        "status",
        "stage",
        "progress",
        "started_at",
        "created_at",
    ]
    list_filter = ["status", "rollback_status", "service"]
    search_fields = ["name", "service__name", "status_message", "error_message"]
    ordering = ["-created_at"]
    list_per_page = 50
    panels = panels_for(
        editable=["name", "service", "version", "zip_file"],
        read_only=[
            "id",
            "config",
            "started_at",
            "completed_at",
            "updated_file_at",
            "status",
            "stage",
            "progress",
            "status_message",
            "error_message",
            "rollback_status",
            "health_status",
            "container_status",
            "image_status",
            "volume_status",
            "network_status",
            "cancel_requested",
            "created_at",
            "updated_at",
        ],
    )


class ReadOnlyModelPermissionPolicy(ModelPermissionPolicy):
    """Permission policy that only allows listing/reading, never mutating."""

    def user_has_permission(self, user, action):
        if action in {"add", "change", "delete"}:
            return False
        return super().user_has_permission(user, action)

    def user_has_any_permission(self, user, actions):
        actions = {a for a in actions if a not in {"add", "change", "delete"}}
        return super().user_has_any_permission(user, actions)


class DeployLogViewSet(SnippetViewSet):
    model = DeployLog
    icon = "doc-full-inverse"
    menu_label = _("Deploy logs")
    menu_order = 105
    permission_policy = ReadOnlyModelPermissionPolicy(DeployLog)
    list_display = [
        "deploy_id",
        "service_id",
        "stage",
        "event_type",
        "level",
        "progress",
        "created_at",
    ]
    list_filter = ["stage", "level", "event_type", "created_at"]
    search_fields = ["message", "event_type", "exception_type", "traceback"]
    ordering = ["-created_at"]
    list_per_page = 50
    # Log rows are generated by the deployment pipeline and must never be
    # created/edited by hand, so every field is read-only.
    panels = read_only_panels(
        [
            "id",
            "deploy",
            "service",
            "stage",
            "event_type",
            "level",
            "message",
            "progress",
            "details",
            "exception_type",
            "traceback",
            "created_at",
            "updated_at",
        ]
    )

    def get_queryset(self, request):
        alias = getattr(settings, "DEPLOYMENT_LOG_DB_ALIAS", "default")
        return super().get_queryset(request).using(alias)


class DeployGroup(SnippetViewSetGroup):
    items = (
        DeployViewSet,
        DeployLogViewSet,
    )
    menu_label = _("Deploy")
    menu_icon = "upload"
    menu_order = 104
