# Generated by Django 5.2 on 2026-02-07 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='container',
        ),
        migrations.AddField(
            model_name='volume',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='services.service', verbose_name='Service'),
            preserve_default=False,
        ),
    ]
