# Generated by Django 5.2 on 2025-08-05 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatenetwork',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='service',
            name='previous_network_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='previous_user_email',
        ),
        migrations.RemoveField(
            model_name='service',
            name='previous_user_username',
        ),
        migrations.AddField(
            model_name='privatenetwork',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Network'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privatenetwork',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.privatenetwork', verbose_name='Private Network'),
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
    ]
