# Generated by Django 5.2 on 2026-02-09 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_remove_deploy_running'),
        ('services', '0002_remove_volume_container_volume_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='volume',
            name='unique_bind_per_container',
        ),
        migrations.AddField(
            model_name='service',
            name='selected_deploy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='deploy.deploy', verbose_name='Selected Deploy'),
        ),
        migrations.AddConstraint(
            model_name='volume',
            constraint=models.UniqueConstraint(fields=('bind', 'service'), name='unique_bind_per_service'),
        ),
    ]
