# Generated by Django 5.2 on 2026-02-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_volume_unique_bind_per_container_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('stopped', 'stopped'), ('queued', 'queued'), ('deploying', 'deploying'), ('failed', 'failed'), ('succeeded', 'succeeded')], default='stopped', verbose_name='Deploy Status'),
        ),
    ]
