# Generated by Django 5.2 on 2025-08-10 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_alter_deploy_service'),
        ('services', '0003_remove_service_network_remove_service_plan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
