# Generated by Django 5.2 on 2025-08-10 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_delete_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='volumes',
        ),
        migrations.AddField(
            model_name='volume',
            name='container',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='container', to='services.container', verbose_name='Container'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='volume',
            constraint=models.UniqueConstraint(fields=('bind', 'container'), name='unique_bind_per_container'),
        ),
    ]
