# Generated by Django 5.2.11 on 2026-02-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_read_only_alter_service_selected_deploy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deploy_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
