# Generated by Django 6.0.6 on 2026-07-09 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_deploy_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volumes', to='services.service', verbose_name='Service'),
        ),
    ]
