# Generated by Django 6.0.6 on 2026-08-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_volume_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='read_only',
            field=models.BooleanField(default=True, verbose_name='Read only'),
        ),
    ]
