# Generated by Django 5.2.11 on 2026-09-25 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0015_callsessionparticipant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='callsessionparticipant',
            new_name='messenger_c_call_id_2067d1_idx',
            old_name='messenger_ca_call_id_6fbf5a_idx',
        ),
        migrations.RenameIndex(
            model_name='callsessionparticipant',
            new_name='messenger_c_user_id_c5bae6_idx',
            old_name='messenger_ca_user_id_a9f2f8_idx',
        ),
    ]
