# Generated by Django 5.2 on 2025-07-30 23:12

import django.contrib.auth.models
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='User has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.CharField(default=users.models.get_uuid, editable=False, max_length=32, unique=True)),
                ('username', models.CharField(help_text='Required. 32 characters or fewer. Include numbers, letters and ./-/_ characters.', max_length=32, unique=True, verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email address')),
                ('email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='phone number')),
                ('phone_number_verified', models.BooleanField(default=False, verbose_name='phone number verified')),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='light', max_length=7, verbose_name='theme')),
                ('color', models.PositiveSmallIntegerField(choices=[(0, '#1abc9c'), (1, '#2ecc71'), (2, '#3498db'), (3, '#9b59b6'), (4, '#34495e'), (5, '#16a085'), (6, '#27ae60'), (7, '#2980b9'), (8, '#8e44ad'), (9, '#2c3e50'), (10, '#f1c40f'), (11, '#e67e22'), (12, '#e74c3c'), (13, '#ecf0f1'), (14, '#95a5a6'), (15, '#f39c12'), (16, '#d35400'), (17, '#c0392b'), (18, '#bdc3c7'), (19, '#7f8c8d')], default=users.models.get_color, verbose_name='color')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='users.user', verbose_name='user rule')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='images', validators=[users.models.ImageValidator(max_h=1440, max_w=2560, size_kb=2048)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
