# Generated by Django 5.2 on 2025-07-31 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
