# Generated by Django 6.0.6 on 2026-08-06 19:25

import auth_users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0003_loginsettings_authcode_attempts_authcode_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsettings',
            name='require_invite_for_signup',
            field=models.BooleanField(default=False, help_text='When True (recommended when allow_auto_signup is False), a valid invite token is mandatory to create a new account.'),
        ),
        migrations.AlterField(
            model_name='loginsettings',
            name='allow_auto_signup',
            field=models.BooleanField(default=True, help_text='If user does not exist, automatically create the account. When False, signup is only possible via a valid invite link.'),
        ),
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=auth_users.models.generate_invite_token, editable=False, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, default='', help_text="Optional internal note (e.g. 'Beta testers batch 3')", max_length=120)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of successful signups. Leave empty for unlimited.', null=True)),
                ('uses_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry datetime. Leave empty for no expiry.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invite Link',
                'verbose_name_plural': 'Invite Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InviteUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='auth_users.invitelink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invite Usage',
                'verbose_name_plural': 'Invite Usages',
                'ordering': ['-used_at'],
                'unique_together': {('invite', 'user')},
            },
        ),
    ]
