"""Generic Wagtail administration for Django models not needing bespoke workflows.

The project keeps hand-written viewsets for models with special lifecycle rules.
This module covers the remaining application models so the Wagtail admin exposes
one consistent CRUD/inspect surface without duplicating dozens of near-identical
classes.

Generated forms include every editable local field. Fields marked editable=False,
primary keys, and auto-managed timestamps are read-only. Operational/audit models
can be registered as read-only through READ_ONLY_MODELS.
"""
from __future__ import annotations

from django.apps import apps
from django.db import models as django_models
from django.utils.translation import gettext_lazy as _
from wagtail.admin.panels import FieldPanel
from wagtail.permission_policies.base import ModelPermissionPolicy
from wagtail.snippets.views.snippets import SnippetViewSet, SnippetViewSetGroup


# Models already have bespoke Wagtail viewsets and must not be registered twice.
MODEL_LABELS = (
    "app_catalog.ApplicationInstance",
    "app_catalog.ApplicationInstanceService",
    "auth_users.LoginSettings",
    "auth_users.InviteLink",
    "auth_users.InviteUsage",
    "auth_users.AuthCode",
    "auth_users.LoginLog",
    "core.SystemSetting",
    "custom_emails.EmailTemplate",
    "custom_emails.EmailLog",
    "deploy.Deploy",
    "deploy.DeployLog",
    "deploy.BaseRuntimeImage",
    "deploy.BaseRuntimeImageLease",
    "docs.DocumentCategory",
    "docs.Document",
    "docs.DocumentAsset",
    "logs.ServiceLogStream",
    "logs.ServiceLogEntry",
    "logs.ServiceLogUsage",
    "logs.LogUsageDaily",
    "logs.CollectorHeartbeat",
    "messenger.UserBio",
    "messenger.Contact",
    "messenger.Block",
    "messenger.ProfilePhotoPrivacy",
    "messenger.ProfilePhotoAllowed",
    "messenger.Conversation",
    "messenger.ConversationParticipant",
    "messenger.GroupInviteLink",
    "messenger.JoinRequest",
    "messenger.Message",
    "messenger.MessageReaction",
    "messenger.MessageReadReceipt",
    "messenger.MessageAttachment",
    "messenger.AttachmentViewOnceOpen",
    "messenger.PinnedMessage",
    "messenger.CallSession",
    "messenger.CallSessionParticipant",
    "plans.Plan",
    "services.PrivateNetwork",
    "services.Service",
    "services.Volume",
    "services.ServiceShare",
    "services.ServiceShareMember",
    "services.ServiceShareEvent",
    "services.ShellSession",
    "services.ShellAuditEvent",
    "tickets.Department",
    "tickets.DepartmentMembership",
    "tickets.Ticket",
    "tickets.TicketMessage",
    "tickets.TicketReadState",
    "tickets.TicketAttachment",
    "users.User",
    "users.Receipt",
    "users.Profile",
    "users.Rule",
)

BESPOKE = {
    "auth_users.LoginSettings", "auth_users.InviteLink", "auth_users.InviteUsage",
    "auth_users.AuthCode", "auth_users.LoginLog",
    "custom_emails.EmailTemplate", "custom_emails.EmailLog",
    "deploy.Deploy", "deploy.DeployLog", "deploy.BaseRuntimeImage",
    "messenger.UserBio", "messenger.Contact", "messenger.Block",
    "messenger.ProfilePhotoPrivacy", "messenger.ProfilePhotoAllowed",
    "messenger.Conversation", "messenger.ConversationParticipant",
    "messenger.GroupInviteLink", "messenger.JoinRequest", "messenger.Message",
    "messenger.MessageReaction", "messenger.MessageReadReceipt",
    "messenger.MessageAttachment", "messenger.AttachmentViewOnceOpen",
    "messenger.PinnedMessage", "messenger.CallSession",
    "plans.Plan", "services.PrivateNetwork", "services.Service", "services.Volume",
    "tickets.Department", "tickets.DepartmentMembership", "tickets.Ticket",
    "tickets.TicketMessage", "tickets.TicketReadState", "tickets.TicketAttachment",
    "users.User", "users.Receipt", "users.Profile", "users.Rule",
}

# These models are generated by workers or are audit/history records. They are
# intentionally inspectable but not hand-editable from the admin.
READ_ONLY_MODELS = {
    "app_catalog.ApplicationInstanceService",
    "deploy.BaseRuntimeImageLease",
    "logs.ServiceLogStream",
    "logs.ServiceLogEntry",
    "logs.ServiceLogUsage",
    "logs.LogUsageDaily",
    "logs.CollectorHeartbeat",
    "services.ServiceShareEvent",
    "services.ShellAuditEvent",
}

# Secret/token fields should never appear as writable controls in the universal
# admin. Bespoke admin can provide more specialized handling where necessary.
SENSITIVE_READ_ONLY_FIELDS = {
    "password", "token", "token_hash", "secret_config", "private_key",
    "api_key", "signing_key", "lease_token",
}


class ReadOnlyGeneratedPolicy(ModelPermissionPolicy):
    def user_has_permission(self, user, action):
        if action in {"add", "change", "delete"}:
            return False
        return super().user_has_permission(user, action)

    def user_has_any_permission(self, user, actions):
        allowed = {action for action in actions if action not in {"add", "change", "delete"}}
        return super().user_has_any_permission(user, allowed)


def _local_fields(model):
    fields = []
    for field in model._meta.get_fields():
        if getattr(field, "auto_created", False) and not getattr(field, "concrete", False):
            continue
        if getattr(field, "many_to_many", False) and getattr(field, "auto_created", False):
            continue
        if not getattr(field, "concrete", True) and not getattr(field, "many_to_many", False):
            continue
        fields.append(field)
    return fields


def _field_name(field):
    return getattr(field, "name", str(field))


def _read_only_names(model, *, force_read_only=False):
    names = set()
    for field in _local_fields(model):
        name = _field_name(field)
        if (
            force_read_only
            or getattr(field, "primary_key", False)
            or not getattr(field, "editable", True)
            or getattr(field, "auto_now", False)
            or getattr(field, "auto_now_add", False)
        ):
            names.add(name)
        if name.lower() in SENSITIVE_READ_ONLY_FIELDS:
            names.add(name)
    return names


def _panels(model, *, force_read_only=False):
    readonly = _read_only_names(model, force_read_only=force_read_only)
    panels = []
    for field in _local_fields(model):
        name = _field_name(field)
        panels.append(FieldPanel(name, read_only=name in readonly))
    return panels


def _search_fields(model):
    out = []
    for field in _local_fields(model):
        name = _field_name(field)
        if isinstance(field, (django_models.CharField, django_models.TextField, django_models.EmailField, django_models.SlugField)):
            out.append(name)
    return out[:8]


def _list_filter(model):
    out = []
    for field in _local_fields(model):
        name = _field_name(field)
        if getattr(field, "choices", None) or isinstance(field, django_models.BooleanField):
            out.append(name)
    return out[:8]


def _list_display(model):
    fields = _local_fields(model)
    names = {_field_name(field): field for field in fields}
    preferred = (
        "name", "title", "key", "slug", "username", "email", "status",
        "platform", "user", "service", "category", "is_active", "created_at",
    )
    picked = [name for name in preferred if name in names]
    if not picked:
        picked = [_field_name(field) for field in fields[:4]]
    return picked[:6] or ["__str__"]


def _viewset_class(model, *, read_only=False):
    label = f"{model._meta.app_label}.{model.__name__}"
    attrs = {
        "model": model,
        "icon": "table",
        "menu_label": str(model._meta.verbose_name_plural).title(),
        "menu_order": 400,
        "list_display": _list_display(model),
        "list_filter": _list_filter(model),
        "search_fields": _search_fields(model),
        "ordering": ("-created_at",) if any(
            field.name == "created_at" for field in model._meta.fields
        ) else None,
        "panels": _panels(model, force_read_only=read_only),
        "inspect_view_enabled": True,
        "copy_view_enabled": not read_only,
        "add_to_reference_index": False,
        "__module__": __name__,
    }
    if read_only:
        attrs["permission_policy"] = ReadOnlyGeneratedPolicy(model)
    return type(f"Universal{model.__name__}ViewSet", (SnippetViewSet,), attrs)


def _candidate_viewsets():
    out = []
    for label in MODEL_LABELS:
        if label in BESPOKE:
            continue
        model = apps.get_model(label)
        if model is None:
            continue
        out.append(
            _viewset_class(
                model,
                read_only=label in READ_ONLY_MODELS,
            )
        )
    return tuple(out)


class UniversalModelsGroup(SnippetViewSetGroup):
    items = _candidate_viewsets()
    menu_label = _("Data")
    menu_icon = "table"
    menu_order = 400
