# Generated by Django 6.0.6 on 2026-08-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Stable machine key, e.g. mirror.python or build.max_cpu', max_length=128, unique=True, verbose_name='Key')),
                ('value', models.TextField(blank=True, default='', help_text='Stored as text; cast using value_type.', verbose_name='Value')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=16, verbose_name='Value type')),
                ('category', models.CharField(choices=[('mirrors', 'Registry / package mirrors'), ('runtime', 'Default runtime versions'), ('ports', 'Default ports'), ('build', 'Docker image build limits'), ('deploy', 'Deployment behaviour'), ('dockerfile', 'Dockerfile templates'), ('general', 'General')], db_index=True, default='general', max_length=32, verbose_name='Category')),
                ('label', models.CharField(blank=True, default='', max_length=128, verbose_name='Label')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_secret', models.BooleanField(default=False, help_text='Hide raw value in non-staff API responses.', verbose_name='Secret')),
                ('is_editable', models.BooleanField(default=True, help_text='If false, admin/API cannot change this key.', verbose_name='Editable')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System setting',
                'verbose_name_plural': 'System settings',
                'ordering': ('category', 'key'),
            },
        ),
    ]
