# Generated by Django 5.2.11 on 2026-09-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_core_settings_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='category',
            field=models.CharField(choices=[('mirrors', 'Registry / package mirrors'), ('runtime', 'Default runtime versions'), ('ports', 'Default ports'), ('build', 'Docker image build limits'), ('deploy', 'Deployment behaviour'), ('dockerfile', 'Dockerfile templates'), ('general', 'General'), ('logging', 'Runtime logging'), ('shell', 'Restricted shell')], db_index=True, default='general', max_length=32, verbose_name='Category'),
        ),
    ]
