# Generated by Django 6.0.6 on 2026-08-14 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_join_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_video', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ringing', 'Ringing'), ('active', 'Active'), ('ended', 'Ended'), ('missed', 'Missed'), ('declined', 'Declined'), ('no_answer', 'No answer')], db_index=True, default='ringing', max_length=16)),
                ('room_name', models.CharField(blank=True, default='', max_length=120)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='conversationparticipant',
            new_name='messenger_c_user_id_fd50d0_idx',
            old_name='messenger_cp_user_pin_idx',
        ),
        migrations.RenameIndex(
            model_name='messagereadreceipt',
            new_name='messenger_m_message_355847_idx',
            old_name='messenger_mrr_msg_user_idx',
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='messagereadreceipt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userbio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='messenger.conversation'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='end_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messenger.message'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='initiator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messenger_calls_started', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callsession',
            name='start_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messenger.message'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['conversation', 'status'], name='messenger_c_convers_e7dd37_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['conversation', '-started_at'], name='messenger_c_convers_c5cc92_idx'),
        ),
    ]
