# Generated by Django 6.0.6 on 2026-08-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_scheduled_messages'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='messenger_m_is_sche_79ff54_idx',
            old_name='messenger_m_is_sche_idx',
        ),
    ]
