# Generated by Django 6.0.6 on 2026-08-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_attachment_spoiler_view_once'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attachmentviewonceopen',
            new_name='messenger_a_attachm_5536c2_idx',
            old_name='messenger_a_attachm_viewonce_idx',
        ),
    ]
