# Generated by Django 5.2.11 on 2026-02-10 22:37

import deploy.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('version', models.DecimalField(decimal_places=2, default=0.0, help_text='Deployment version, e.g., 1.0', max_digits=5, verbose_name='Version')),
                ('zip_file', models.FileField(blank=True, null=True, upload_to=deploy.models.zip_file_path, verbose_name='ZIP File')),
                ('config', models.JSONField(blank=True, null=True, verbose_name='Configuration')),
                ('started_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Start Time')),
            ],
            options={
                'verbose_name': 'Deployment',
                'verbose_name_plural': 'Deployments',
            },
        ),
    ]
