# Generated by Django 5.2.11 on 2026-02-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='updated_file_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
