# Generated by Django 5.2 on 2026-02-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_deploy_updated_file_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deploy',
            options={'verbose_name': 'Deploy', 'verbose_name_plural': 'Deploy'},
        ),
    ]
