# Generated by Django 5.2.11 on 2026-09-25 01:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0018_merge_deploy_name_and_swarm'),
        ('services', '0027_rename_service_port_res_host_protocol_state_services_se_host_po_f50e1a_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='baseruntimeimagelease',
            new_name='deploy_base_base_im_05f7bb_idx',
            old_name='deploy_base_base_imag_lease_idx',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='operation_previous_resource_id',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='operation_resource_id',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='operation_started_at',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='recovery_metadata',
        ),
        migrations.AlterField(
            model_name='baseruntimeimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='baseruntimeimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='baseruntimeimagelease',
            name='acquired_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='baseruntimeimagelease',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='baseruntimeimagelease',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='revision',
            field=models.ForeignKey(blank=True, help_text='Immutable service configuration snapshot executed by this deployment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='services.servicerevision', verbose_name='Service Revision'),
        ),
        migrations.AlterField(
            model_name='swarmcluster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='swarmcluster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='swarmnode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='swarmnode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
