# Generated by Django 6.0.6 on 2026-09-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0019_rename_deploy_base_base_imag_lease_idx_deploy_base_base_im_05f7bb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='operation',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='deploy',
            name='operation_previous_resource_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deploy',
            name='operation_resource_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deploy',
            name='operation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deploy',
            name='recovery_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
