# Generated by Django 5.2 on 2025-08-02 15:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('platform', models.CharField(choices=[], max_length=20, verbose_name='Platform')),
                ('max_cpu', models.IntegerField(verbose_name='Maximum CPU (vCPU)')),
                ('max_ram', models.IntegerField(verbose_name='Maximum RAM (MB)')),
                ('max_storage', models.IntegerField(verbose_name='Maximum Storage (GB)')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Toman', max_digits=10, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
    ]
